# Site settings
title: Jon Dueck
email: hi@jondueck.ca
description: > # this means to ignore newlines until "baseurl:"
  Brand designer and front-end web developer from Winkler, Manitoba. Partner at Collectif. Personal site, blog, and portfolio.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jondueck.ca" # the base hostname & protocol for your site
twitter: jondueck
github: jondueck
permalink: /:year/:title/
exclude: ['/node_modules/','**.sublime-project','**.sublime-workspace','gulpfile.js','package.json','.git','README.md']

gems:
  - jekyll-last-modified-at
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  # - jekyll-srcset

# Build settings
markdown: kramdown
theme: null
# paginate: 4

collections:
  work:
    title: Work
    output: true
    permalink: /work/:path/
  journal:
    title: Journal
    output: true
    permalink: /journal/:year/:title/
    paginate: 8
    paginate_path: "/journal/page:num/"
    pagination:
      enabled: true
      permalink: "/journal/page:num"
      per_page: 10
  uploads:
    title: Uploads
    output: true
  eat:
    title: Eat
    output: true
    permalink: /eat/:path/
defaults:
- scope:
    path: '/_posts/'
    type: journal
  values:
    layout: post
    author: Jon Dueck
- scope:
    path: '/_work/'
    type: work
  values:
    # layout: work-post
    author: Jon Dueck
- scope:
    path: '/_eat/'
    type: eat
  values:
    layout: post
    author: Jon Dueck
